### ISSUE TITLE
There's some kind of issue with cloning the submodule

### ISSUE THREAD

**Issue by omarandlorraine** [omarandlorraine/stoc#1]
What you're supposed to do to clone this is:
`git clone --recursive git@github.com:omarandlorraine/stoc.git`

BUT Something's up with the submodule thing which means fake6502 doesn't get cloned, I haven't figured it out yet

**Comment by retrac0** [comment]
Any chance of a tarball until you figure it out?  I'd love to try this on some short routines in my code and see if it comes up with anything!

**Comment by omarandlorraine** [comment]
> Any chance of a tarball until you figure it out? I'd love to try this on some short routines in my code and see if it comes up with anything!

One way round this is:
```
git clone git@github.com:omarandlorraine/stoc.git
cd stoc
git clone git@github.com:omarandlorraine/fake6502.git
```

The submodule has now been cloned separately, and you can now build all the executables with `make`. 

Oh, and do let me know if you find anything interesting, or any problems at all!

**Comment by omarandlorraine** [comment]
Actually, I fixed it.

You can just do `git clone --recursive git@github.com:omarandlorraine/stoc.git`, and the submodule will get cloned as well
